/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *       Sam Padgett          - initial API and implementation
 *     Michael Fiedler      - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (422448)
 *     Matthieu Helleboid   - Support for multiple Service Providers.
 *     Anass Radouani       - Support for multiple Service Providers.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package se.ericsson.cf.scott.sandbox.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;
import javax.servlet.http.HttpServletRequest;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import javax.ws.rs.core.UriBuilder;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;

import se.ericsson.cf.scott.sandbox.TwinConstants;
import se.ericsson.cf.scott.sandbox.resources.Variable;

// Start of user code imports
// End of user code

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// End of user code
@OslcNamespace(TwinConstants.PLANNING_NAMSPACE)
@OslcName(TwinConstants.VARIABLEINSTANCE)
@OslcResourceShape(title = "VariableInstance Resource Shape", describes = TwinConstants.TYPE_VARIABLEINSTANCE)
public class VariableInstance
    extends AbstractResource
    implements IVariableInstance
{
    // Start of user code attributeAnnotation:value
    // End of user code
    private Link value = new Link();
    // Start of user code attributeAnnotation:label
    // End of user code
    private String label;
    // Start of user code attributeAnnotation:order
    // End of user code
    private Integer order;
    // Start of user code attributeAnnotation:ppInstanceOf
    // End of user code
    private Link ppInstanceOf = new Link();
    
    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    // End of user code
    public VariableInstance()
           throws URISyntaxException
    {
        super();
    
        // Start of user code constructor1
        // End of user code
    }
    
    public VariableInstance(final URI about)
           throws URISyntaxException
    {
        super(about);
    
        // Start of user code constructor2
        // End of user code
    }
    
    
    public static ResourceShape createResourceShape() throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(OSLC4JUtils.getServletURI(),
        OslcConstants.PATH_RESOURCE_SHAPES,
        TwinConstants.PATH_VARIABLEINSTANCE,
        VariableInstance.class);
    }
    
    
    public String toString()
    {
        return toString(false);
    }
    
    public String toString(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toString_init
        // End of user code
    
        if (asLocalResource) {
            result = result + "{a Local VariableInstance Resource} - update VariableInstance.toString() to present resource as desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        }
        else {
            result = getAbout().toString();
        }
    
        // Start of user code toString_finalize
        // End of user code
    
        return result;
    }
    
    public String toHtml()
    {
        return toHtml(false);
    }
    
    public String toHtml(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toHtml_init
        // End of user code
    
        if (asLocalResource) {
            result = toString(true);
            // Start of user code toHtml_bodyForLocalResource
            // End of user code
        }
        else {
            result = "<a href=\"" + getAbout() + "\">" + toString() + "</a>";
        }
    
        // Start of user code toHtml_finalize
        // End of user code
    
        return result;
    }
    
    
    // Start of user code getterAnnotation:value
    // End of user code
    @OslcName("value")
    @OslcPropertyDefinition(TwinConstants.PLANNING_NAMSPACE + "value")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.LocalResource)
    @OslcReadOnly(false)
    public Link getValue()
    {
        // Start of user code getterInit:value
        // End of user code
        return value;
    }
    
    // Start of user code getterAnnotation:label
    // End of user code
    @OslcName("label")
    @OslcPropertyDefinition(TwinConstants.RDFS_NAMSPACE + "label")
    @OslcDescription("May be used to provide a human-readable version of a resource's name.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.XMLLiteral)
    @OslcReadOnly(false)
    public String getLabel()
    {
        // Start of user code getterInit:label
        // End of user code
        return label;
    }
    
    // Start of user code getterAnnotation:order
    // End of user code
    @OslcName("order")
    @OslcPropertyDefinition(TwinConstants.PLANNING_NAMSPACE + "order")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.Integer)
    @OslcReadOnly(false)
    public Integer getOrder()
    {
        // Start of user code getterInit:order
        // End of user code
        return order;
    }
    
    // Start of user code getterAnnotation:ppInstanceOf
    // End of user code
    @OslcName("ppInstanceOf")
    @OslcPropertyDefinition(TwinConstants.PLANNING_NAMSPACE + "ppInstanceOf")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.Resource)
    @OslcRange({TwinConstants.TYPE_VARIABLE})
    @OslcReadOnly(false)
    @OslcTitle("")
    public Link getPpInstanceOf()
    {
        // Start of user code getterInit:ppInstanceOf
        // End of user code
        return ppInstanceOf;
    }
    
    
    // Start of user code setterAnnotation:value
    // End of user code
    public void setValue(final Link value )
    {
        // Start of user code setterInit:value
        // End of user code
        this.value = value;
    
        // Start of user code setterFinalize:value
        // End of user code
    }
    
    // Start of user code setterAnnotation:label
    // End of user code
    public void setLabel(final String label )
    {
        // Start of user code setterInit:label
        // End of user code
        this.label = label;
    
        // Start of user code setterFinalize:label
        // End of user code
    }
    
    // Start of user code setterAnnotation:order
    // End of user code
    public void setOrder(final Integer order )
    {
        // Start of user code setterInit:order
        // End of user code
        this.order = order;
    
        // Start of user code setterFinalize:order
        // End of user code
    }
    
    // Start of user code setterAnnotation:ppInstanceOf
    // End of user code
    public void setPpInstanceOf(final Link ppInstanceOf )
    {
        // Start of user code setterInit:ppInstanceOf
        // End of user code
        this.ppInstanceOf = ppInstanceOf;
    
        // Start of user code setterFinalize:ppInstanceOf
        // End of user code
    }
    
    
    static public String valueToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:valueToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"value\">value: </LABEL>";
    
        // Start of user code "Mid:valueToHtmlForCreation(...)"
        // End of user code
    
        // Start of user code "Finalize:valueToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    static public String labelToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:labelToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"label\">label: </LABEL>";
    
        // Start of user code "Mid:labelToHtmlForCreation(...)"
        // End of user code
    
        s= s + "<input name=\"label\" type=\"text\" style=\"width: 400px\" id=\"label\" >";
        // Start of user code "Finalize:labelToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    static public String orderToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:orderToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"order\">order: </LABEL>";
    
        // Start of user code "Mid:orderToHtmlForCreation(...)"
        // End of user code
    
        s= s + "<input name=\"order\" type=\"text\" style=\"width: 400px\" id=\"order\" >";
        // Start of user code "Finalize:orderToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    static public String ppInstanceOfToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:ppInstanceOfToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"instanceOf\">instanceOf: </LABEL>";
    
        // Start of user code "Mid:ppInstanceOfToHtmlForCreation(...)"
        // End of user code
    
        // Start of user code "Finalize:ppInstanceOfToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    
    public String valueToHtml()
    {
        String s = "";
    
        // Start of user code valuetoHtml_init
        // End of user code
    
        s = s + "<label for=\"value\"><strong>value</strong>: &nbsp;</LABEL>";
    
        // Start of user code valuetoHtml_mid
        // End of user code
    
        try {
            if ((value == null) || (value.getValue() == null)) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + value.getValue().toString();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code valuetoHtml_finalize
        // End of user code
    
        return s;
    }
    
    public String labelToHtml()
    {
        String s = "";
    
        // Start of user code labeltoHtml_init
        // End of user code
    
        s = s + "<label for=\"label\"><strong>label</strong>: &nbsp;</LABEL>";
    
        // Start of user code labeltoHtml_mid
        // End of user code
    
        try {
            if (label == null) {
                s= s + "<em>null</em>";
            }
            else {
                s= s + label.toString();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code labeltoHtml_finalize
        // End of user code
    
        return s;
    }
    
    public String orderToHtml()
    {
        String s = "";
    
        // Start of user code ordertoHtml_init
        // End of user code
    
        s = s + "<label for=\"order\"><strong>order</strong>: &nbsp;</LABEL>";
    
        // Start of user code ordertoHtml_mid
        // End of user code
    
        try {
            if (order == null) {
                s= s + "<em>null</em>";
            }
            else {
                s= s + order.toString();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code ordertoHtml_finalize
        // End of user code
    
        return s;
    }
    
    public String ppInstanceOfToHtml()
    {
        String s = "";
    
        // Start of user code ppInstanceOftoHtml_init
        // End of user code
    
        s = s + "<label for=\"instanceOf\"><strong>instanceOf</strong>: &nbsp;</LABEL>";
    
        // Start of user code ppInstanceOftoHtml_mid
        // End of user code
    
        try {
            if ((ppInstanceOf == null) || (ppInstanceOf.getValue() == null)) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + (new Variable (ppInstanceOf.getValue())).toHtml(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code ppInstanceOftoHtml_finalize
        // End of user code
    
        return s;
    }
    
    
}
