set(_CATKIN_CURRENT_PACKAGE "phantomx_pincher_arm_vrep_controller")
set(phantomx_pincher_arm_vrep_controller_VERSION "1.0.0")
set(phantomx_pincher_arm_vrep_controller_MAINTAINER "Amadeu do Nascimento Júnior <amadeu.nascimento.junior@ericsson.com>")
set(phantomx_pincher_arm_vrep_controller_PACKAGE_FORMAT "1")
set(phantomx_pincher_arm_vrep_controller_BUILD_DEPENDS "roscpp" "std_msgs")
set(phantomx_pincher_arm_vrep_controller_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "rosconsole" "roslib")
set(phantomx_pincher_arm_vrep_controller_BUILDTOOL_DEPENDS "catkin")
set(phantomx_pincher_arm_vrep_controller_BUILDTOOL_EXPORT_DEPENDS )
set(phantomx_pincher_arm_vrep_controller_EXEC_DEPENDS "roscpp" "std_msgs" "rosconsole" "roslib")
set(phantomx_pincher_arm_vrep_controller_RUN_DEPENDS "roscpp" "std_msgs" "rosconsole" "roslib")
set(phantomx_pincher_arm_vrep_controller_TEST_DEPENDS )
set(phantomx_pincher_arm_vrep_controller_DOC_DEPENDS )
set(phantomx_pincher_arm_vrep_controller_URL_WEBSITE "")
set(phantomx_pincher_arm_vrep_controller_URL_BUGTRACKER "")
set(phantomx_pincher_arm_vrep_controller_URL_REPOSITORY "")
set(phantomx_pincher_arm_vrep_controller_DEPRECATED "")