// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package eu.scott.warehouse.domains.scott;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface ScottDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String SCOTT_WAREHOUSE_DOMAIN = "http://ontology.cf.ericsson.net/ns/scott-warehouse/";
    public static String SCOTT_WAREHOUSE_NAMSPACE = "http://ontology.cf.ericsson.net/ns/scott-warehouse/";
    public static String SCOTT_WAREHOUSE_NAMSPACE_PREFIX = "scott";

    public static String BOX_PATH = "box";
    public static String BOX_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String BOX_LOCALNAME = "Box"; //localName of the rdfs:class the resource describes
    public static String BOX_TYPE = BOX_NAMESPACE + BOX_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String CONVEYORBELT_PATH = "conveyorBelt";
    public static String CONVEYORBELT_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String CONVEYORBELT_LOCALNAME = "ConveyorBelt"; //localName of the rdfs:class the resource describes
    public static String CONVEYORBELT_TYPE = CONVEYORBELT_NAMESPACE + CONVEYORBELT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String COORD_PATH = "coord";
    public static String COORD_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String COORD_LOCALNAME = "Coord"; //localName of the rdfs:class the resource describes
    public static String COORD_TYPE = COORD_NAMESPACE + COORD_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String EXECUTABLEACTION_PATH = "executableAction";
    public static String EXECUTABLEACTION_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String EXECUTABLEACTION_LOCALNAME = "ExecutableAction"; //localName of the rdfs:class the resource describes
    public static String EXECUTABLEACTION_TYPE = EXECUTABLEACTION_NAMESPACE + EXECUTABLEACTION_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String ROBOT_PATH = "robot";
    public static String ROBOT_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String ROBOT_LOCALNAME = "Robot"; //localName of the rdfs:class the resource describes
    public static String ROBOT_TYPE = ROBOT_NAMESPACE + ROBOT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String SHELF_PATH = "shelf";
    public static String SHELF_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String SHELF_LOCALNAME = "Shelf"; //localName of the rdfs:class the resource describes
    public static String SHELF_TYPE = SHELF_NAMESPACE + SHELF_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String DROP_BELT_PATH = "dropBelt";
    public static String DROP_BELT_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String DROP_BELT_LOCALNAME = "drop-belt"; //localName of the rdfs:class the resource describes
    public static String DROP_BELT_TYPE = DROP_BELT_NAMESPACE + DROP_BELT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String MOVE_TO_WP_PATH = "moveToWp";
    public static String MOVE_TO_WP_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String MOVE_TO_WP_LOCALNAME = "move-to-wp"; //localName of the rdfs:class the resource describes
    public static String MOVE_TO_WP_TYPE = MOVE_TO_WP_NAMESPACE + MOVE_TO_WP_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PICK_SHELF_PATH = "pickShelf";
    public static String PICK_SHELF_NAMESPACE = SCOTT_WAREHOUSE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PICK_SHELF_LOCALNAME = "pick-shelf"; //localName of the rdfs:class the resource describes
    public static String PICK_SHELF_TYPE = PICK_SHELF_NAMESPACE + PICK_SHELF_LOCALNAME; //fullname of the rdfs:class the resource describes
}
