// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *       Sam Padgett          - initial API and implementation
 *     Michael Fiedler      - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (422448)
 *     Matthieu Helleboid   - Support for multiple Service Providers.
 *     Anass Radouani       - Support for multiple Service Providers.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package eu.scott.warehouse.domains.mission;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;
import javax.servlet.http.HttpServletRequest;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import javax.ws.rs.core.UriBuilder;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;

import eu.scott.warehouse.domains.mission.MissionDomainConstants;
import eu.scott.warehouse.domains.mission.Selector;

import eu.scott.warehouse.domains.mission.MissionDomainConstants;
import eu.scott.warehouse.domains.mission.Location;
import eu.scott.warehouse.domains.mission.Selector;

// Start of user code imports
// End of user code

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// End of user code
@OslcNamespace(MissionDomainConstants.LOCATIONSELECTOR_NAMESPACE)
@OslcName(MissionDomainConstants.LOCATIONSELECTOR_LOCALNAME)
@OslcResourceShape(title = "LocationSelector Resource Shape", describes = MissionDomainConstants.LOCATIONSELECTOR_TYPE)
public class LocationSelector
    extends Selector
    implements ILocationSelector
{
    // Start of user code attributeAnnotation:selector
    // End of user code
    private Selector selector = new Selector();
    // Start of user code attributeAnnotation:location
    // End of user code
    private Link location = new Link();
    
    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    // End of user code
    public LocationSelector()
           throws URISyntaxException
    {
        super();
    
        // Start of user code constructor1
        // End of user code
    }
    
    public LocationSelector(final URI about)
           throws URISyntaxException
    {
        super(about);
    
        // Start of user code constructor2
        // End of user code
    }
    
    
    public static ResourceShape createResourceShape() throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(OSLC4JUtils.getServletURI(),
        OslcConstants.PATH_RESOURCE_SHAPES,
        MissionDomainConstants.LOCATIONSELECTOR_PATH,
        LocationSelector.class);
    }
    
    
    public String toString()
    {
        return toString(false);
    }
    
    public String toString(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toString_init
        // End of user code
    
        if (asLocalResource) {
            result = result + "{a Local LocationSelector Resource} - update LocationSelector.toString() to present resource as desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        }
        else {
            result = getAbout().toString();
        }
    
        // Start of user code toString_finalize
        // End of user code
    
        return result;
    }
    
    public String toHtml()
    {
        return toHtml(false);
    }
    
    public String toHtml(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toHtml_init
        // End of user code
    
        if (asLocalResource) {
            result = toString(true);
            // Start of user code toHtml_bodyForLocalResource
            // End of user code
        }
        else {
            result = "<a href=\"" + getAbout() + "\" class=\"oslc-resource-link\">" + toString() + "</a>";
        }
    
        // Start of user code toHtml_finalize
        // End of user code
    
        return result;
    }
    
    
    // Start of user code getterAnnotation:selector
    // End of user code
    @OslcName("selector")
    @OslcPropertyDefinition(MissionDomainConstants.MISSIONONTOLOGY_NAMSPACE + "selector")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.LocalResource)
    @OslcRepresentation(Representation.Reference)
    @OslcRange({MissionDomainConstants.SELECTOR_TYPE})
    @OslcReadOnly(false)
    @OslcTitle("")
    public Selector getSelector()
    {
        // Start of user code getterInit:selector
        // End of user code
        return selector;
    }
    
    // Start of user code getterAnnotation:location
    // End of user code
    @OslcName("location")
    @OslcPropertyDefinition(MissionDomainConstants.MISSIONONTOLOGY_NAMSPACE + "location")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.Resource)
    @OslcRange({MissionDomainConstants.LOCATION_TYPE})
    @OslcReadOnly(false)
    public Link getLocation()
    {
        // Start of user code getterInit:location
        // End of user code
        return location;
    }
    
    
    // Start of user code setterAnnotation:selector
    // End of user code
    public void setSelector(final Selector selector )
    {
        // Start of user code setterInit:selector
        // End of user code
        this.selector = selector;
    
        // Start of user code setterFinalize:selector
        // End of user code
    }
    
    // Start of user code setterAnnotation:location
    // End of user code
    public void setLocation(final Link location )
    {
        // Start of user code setterInit:location
        // End of user code
        this.location = location;
    
        // Start of user code setterFinalize:location
        // End of user code
    }
    
    
    static public String selectorToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:selectorToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"selector\">selector: </LABEL>";
    
        // Start of user code "Mid:selectorToHtmlForCreation(...)"
        // End of user code
    
        // Start of user code "Finalize:selectorToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    static public String locationToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
        String s = "";
    
        // Start of user code "Init:locationToHtmlForCreation(...)"
        // End of user code
    
        s = s + "<label for=\"location\">location: </LABEL>";
    
        // Start of user code "Mid:locationToHtmlForCreation(...)"
        // End of user code
    
        // Start of user code "Finalize:locationToHtmlForCreation(...)"
        // End of user code
    
        return s;
    }
    
    
    public String selectorToHtml()
    {
        String s = "";
    
        // Start of user code selectortoHtml_mid
        // End of user code
    
        try {
            if (selector == null) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + selector.toHtml(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code selectortoHtml_finalize
        // End of user code
    
        return s;
    }
    
    public String locationToHtml()
    {
        String s = "";
    
        // Start of user code locationtoHtml_mid
        // End of user code
    
        try {
            if ((location == null) || (location.getValue() == null)) {
                s = s + "<em>null</em>";
            }
            else {
                s = s + (new Location (location.getValue())).toHtml(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
        // Start of user code locationtoHtml_finalize
        // End of user code
    
        return s;
    }
    
    
}
