version: '3.3'

services:
  planner-reasoner:
    image: "${CI_REGISTRY_IMAGE}/planner-reasoner:${CI_COMMIT_REF_NAME}"
    environment:
      - PORT=3020 # internal port
    networks:
      - overlay
    ports:
      - "3021:3020" # mapping of external port to internal port
    stdin_open: true
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512m
  sandbox-whc:
    image: "${CI_REGISTRY_IMAGE}/webapp-whc:${CI_COMMIT_REF_NAME}"
    networks:
      - overlay
    ports:
      - "8080:8080"
    deploy:
      # not ready for scaling yet
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512m
    depends_on:
      - warehouse-fuseki
      - mosquitto
  sandbox-executor:
    image: "${CI_REGISTRY_IMAGE}/webapp-executor:${CI_COMMIT_REF_NAME}"
    networks:
      - overlay
    ports:
      - "8083:8080"
    depends_on:
      - sandbox-whc
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
  sandbox-twin:
    image: "${CI_REGISTRY_IMAGE}/webapp-twin-robot:${CI_COMMIT_REF_NAME}"
    networks:
      - overlay
    ports:
     - "8081:8080"
    depends_on:
      - warehouse-fuseki
      - mosquitto
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512m
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
  svc-location:
    image: "${CI_REGISTRY_IMAGE}/webapp-svc-location:${CI_COMMIT_REF_NAME}"
    networks:
      - overlay
    ports:
     - "8090:8080"
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512m
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
  warehouse-fuseki:
    image: "${CI_REGISTRY_IMAGE}/jena-fuseki:${CI_COMMIT_REF_NAME}"
    networks:
      - overlay
    ports:
      - "3030:3030"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1024m
  mosquitto:
    image: "${CI_REGISTRY_IMAGE}/eclipse-mosquitto:${CI_COMMIT_REF_NAME}"
    networks:
      - overlay
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 384m

networks:
  overlay:
