// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package eu.scott.warehouse.domains.pddl;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface PddlDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String SCOTT_PDDL_2_1_SUBSET_SPEC_DOMAIN = "http://ontology.cf.ericsson.net/pddl/";
    public static String SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE = "http://ontology.cf.ericsson.net/pddl/";
    public static String SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE_PREFIX = "pddl";

    public static String ACTION_PATH = "action";
    public static String ACTION_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String ACTION_LOCALNAME = "Action"; //localName of the rdfs:class the resource describes
    public static String ACTION_TYPE = ACTION_NAMESPACE + ACTION_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String ASSIGNMENTOPERATOR_PATH = "assignmentOperator";
    public static String ASSIGNMENTOPERATOR_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String ASSIGNMENTOPERATOR_LOCALNAME = "AssignmentOperator"; //localName of the rdfs:class the resource describes
    public static String ASSIGNMENTOPERATOR_TYPE = ASSIGNMENTOPERATOR_NAMESPACE + ASSIGNMENTOPERATOR_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String BINARYCOMPARATOR_PATH = "binaryComparator";
    public static String BINARYCOMPARATOR_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String BINARYCOMPARATOR_LOCALNAME = "BinaryComparator"; //localName of the rdfs:class the resource describes
    public static String BINARYCOMPARATOR_TYPE = BINARYCOMPARATOR_NAMESPACE + BINARYCOMPARATOR_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String BINARYOPERATOR_PATH = "binaryOperator";
    public static String BINARYOPERATOR_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String BINARYOPERATOR_LOCALNAME = "BinaryOperator"; //localName of the rdfs:class the resource describes
    public static String BINARYOPERATOR_TYPE = BINARYOPERATOR_NAMESPACE + BINARYOPERATOR_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String CONSTANT_PATH = "constant";
    public static String CONSTANT_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String CONSTANT_LOCALNAME = "Constant"; //localName of the rdfs:class the resource describes
    public static String CONSTANT_TYPE = CONSTANT_NAMESPACE + CONSTANT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String DOMAIN_PATH = "domain";
    public static String DOMAIN_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String DOMAIN_LOCALNAME = "Domain"; //localName of the rdfs:class the resource describes
    public static String DOMAIN_TYPE = DOMAIN_NAMESPACE + DOMAIN_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String EITHERTYPE_PATH = "eitherType";
    public static String EITHERTYPE_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String EITHERTYPE_LOCALNAME = "EitherType"; //localName of the rdfs:class the resource describes
    public static String EITHERTYPE_TYPE = EITHERTYPE_NAMESPACE + EITHERTYPE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String FLUENTMINUS_PATH = "fluentMinus";
    public static String FLUENTMINUS_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String FLUENTMINUS_LOCALNAME = "FluentMinus"; //localName of the rdfs:class the resource describes
    public static String FLUENTMINUS_TYPE = FLUENTMINUS_NAMESPACE + FLUENTMINUS_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String FORALL_PATH = "forAll";
    public static String FORALL_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String FORALL_LOCALNAME = "ForAll"; //localName of the rdfs:class the resource describes
    public static String FORALL_TYPE = FORALL_NAMESPACE + FORALL_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String FUNCTION_PATH = "function";
    public static String FUNCTION_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String FUNCTION_LOCALNAME = "Function"; //localName of the rdfs:class the resource describes
    public static String FUNCTION_TYPE = FUNCTION_NAMESPACE + FUNCTION_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String IMPLY_PATH = "imply";
    public static String IMPLY_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String IMPLY_LOCALNAME = "Imply"; //localName of the rdfs:class the resource describes
    public static String IMPLY_TYPE = IMPLY_NAMESPACE + IMPLY_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String NOT_PATH = "not";
    public static String NOT_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String NOT_LOCALNAME = "Not"; //localName of the rdfs:class the resource describes
    public static String NOT_TYPE = NOT_NAMESPACE + NOT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String OBJECT_PATH = "object";
    public static String OBJECT_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String OBJECT_LOCALNAME = "Object"; //localName of the rdfs:class the resource describes
    public static String OBJECT_TYPE = OBJECT_NAMESPACE + OBJECT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String OR_PATH = "or";
    public static String OR_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String OR_LOCALNAME = "Or"; //localName of the rdfs:class the resource describes
    public static String OR_TYPE = OR_NAMESPACE + OR_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PARAMETER_PATH = "parameter";
    public static String PARAMETER_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PARAMETER_LOCALNAME = "Parameter"; //localName of the rdfs:class the resource describes
    public static String PARAMETER_TYPE = PARAMETER_NAMESPACE + PARAMETER_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PLAN_PATH = "plan";
    public static String PLAN_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PLAN_LOCALNAME = "Plan"; //localName of the rdfs:class the resource describes
    public static String PLAN_TYPE = PLAN_NAMESPACE + PLAN_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PLANEXECUTIONRESULT_PATH = "planExecutionResult";
    public static String PLANEXECUTIONRESULT_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PLANEXECUTIONRESULT_LOCALNAME = "PlanExecutionResult"; //localName of the rdfs:class the resource describes
    public static String PLANEXECUTIONRESULT_TYPE = PLANEXECUTIONRESULT_NAMESPACE + PLANEXECUTIONRESULT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PREDICATE_PATH = "predicate";
    public static String PREDICATE_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PREDICATE_LOCALNAME = "Predicate"; //localName of the rdfs:class the resource describes
    public static String PREDICATE_TYPE = PREDICATE_NAMESPACE + PREDICATE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PRIMITIVETYPE_PATH = "primitiveType";
    public static String PRIMITIVETYPE_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PRIMITIVETYPE_LOCALNAME = "PrimitiveType"; //localName of the rdfs:class the resource describes
    public static String PRIMITIVETYPE_TYPE = PRIMITIVETYPE_NAMESPACE + PRIMITIVETYPE_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PROBLEM_PATH = "problem";
    public static String PROBLEM_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PROBLEM_LOCALNAME = "Problem"; //localName of the rdfs:class the resource describes
    public static String PROBLEM_TYPE = PROBLEM_NAMESPACE + PROBLEM_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String QUANTIFIER_PATH = "quantifier";
    public static String QUANTIFIER_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String QUANTIFIER_LOCALNAME = "Quantifier"; //localName of the rdfs:class the resource describes
    public static String QUANTIFIER_TYPE = QUANTIFIER_NAMESPACE + QUANTIFIER_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String STEP_PATH = "step";
    public static String STEP_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String STEP_LOCALNAME = "Step"; //localName of the rdfs:class the resource describes
    public static String STEP_TYPE = STEP_NAMESPACE + STEP_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String WHEN_PATH = "when";
    public static String WHEN_NAMESPACE = SCOTT_PDDL_2_1_SUBSET_SPEC_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String WHEN_LOCALNAME = "When"; //localName of the rdfs:class the resource describes
    public static String WHEN_TYPE = WHEN_NAMESPACE + WHEN_LOCALNAME; //fullname of the rdfs:class the resource describes
}
