version: '2'
services:
  planner_reasoner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_HOST=localhost # external host
        - PUBLIC_PORT=3020 # external port
        - PREFIX_PATH=/
        - EXPOSED_PREFIXES=*
    environment:
      - PORT=3020 # internal port
    ports:
      - "3020:3020" # mapping of external port to internal port
    stdin_open: true
