phantom_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - PhantomXPincher_joint1
     - PhantomXPincher_joint2
     - PhantomXPincher_joint3
     - PhantomXPincher_joint4
  publish_rate: 50
gripper_controller:
  type: position_controllers/GripperActionController
  joint: PhantomXPincher_gripperClose_joint
  publish_rate: 50
joint_states:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0
  extra_joints:
    - name: 'wheel_left_joint'
      position: 0.0
    - name: 'wheel_right_joint'
      position: 0.0
