pincher_arm:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 15
  #kinematics_solver_attempts: 200
  # Using IK TRAC because: https://github.com/ros-planning/moveit/issues/343
  position_only_ik: True
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 15
