/*******************************************************************************
 * Copyright (c) 2011, 2012 IBM Corporation and others.
 *
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 *  The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 *  and the Eclipse Distribution License is available at
 *  http://www.eclipse.org/org/documents/edl-v10.php.
 *  
 *  Contributors:
 *  
 *	   Sam Padgett	       - initial API and implementation
 *     Michael Fiedler     - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Matthieu Helleboid   - Support for multiple Service Providers.
 *     Anass Radouani       - Support for multiple Service Providers.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package se.ericsson.cf.scott.sandbox;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.ServletContextEvent;
import java.util.List;

import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import se.ericsson.cf.scott.sandbox.servlet.ServiceProviderCatalogSingleton;
import se.ericsson.cf.scott.sandbox.ServiceProviderInfo;
import se.ericsson.cf.scott.sandbox.resources.Mission;
import se.ericsson.cf.scott.sandbox.resources.Place;
import se.ericsson.cf.scott.sandbox.resources.Predicate;
import se.ericsson.cf.scott.sandbox.resources.ProblemState;
import se.ericsson.cf.scott.sandbox.resources.Robot;
import se.ericsson.cf.scott.sandbox.resources.Waypoint;
import se.ericsson.cf.scott.sandbox.resources.WhObject;


// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code

public class WarehouseControllerManager {

    // Start of user code class_attributes
    // End of user code
    
    
    // Start of user code class_methods
    // End of user code

    public static void contextInitializeServletListener(final ServletContextEvent servletContextEvent)
    {
        
        // Start of user code contextInitializeServletListener
        // TODO Implement code to establish connection to data backbone etc ...
        // End of user code
    }

    public static void contextDestroyServletListener(ServletContextEvent servletContextEvent) 
    {
        
        // Start of user code contextDestroyed
        // TODO Implement code to shutdown connections to data backbone etc...
        // End of user code
    }

    public static ServiceProviderInfo[] getServiceProviderInfos(HttpServletRequest httpServletRequest)
    {
        ServiceProviderInfo[] serviceProviderInfos = {};
        
        // Start of user code "ServiceProviderInfo[] getServiceProviderInfos(...)"
        // TODO Implement code to return the set of ServiceProviders
        // End of user code
        return serviceProviderInfos;
    }

    public static List<WhObject> queryWhObjects(HttpServletRequest httpServletRequest, final String serviceProviderId, String where, int page, int limit)
    {
        List<WhObject> resources = null;
        
        // Start of user code queryWhObjects
        // TODO Implement code to return a set of resources
        // End of user code
        return resources;
    }
    public static List<Place> queryPlaces(HttpServletRequest httpServletRequest, final String serviceProviderId, String where, int page, int limit)
    {
        List<Place> resources = null;
        
        // Start of user code queryPlaces
        // TODO Implement code to return a set of resources
        // End of user code
        return resources;
    }
    public static List<Waypoint> queryWaypoints(HttpServletRequest httpServletRequest, final String serviceProviderId, String where, int page, int limit)
    {
        List<Waypoint> resources = null;
        
        // Start of user code queryWaypoints
        // TODO Implement code to return a set of resources
        // End of user code
        return resources;
    }


    public static Mission getMission(HttpServletRequest httpServletRequest, final String serviceProviderId, final String missionId)
    {
        Mission aResource = null;
        
        // Start of user code getMission
        // TODO Implement code to return a resource
        // End of user code
        return aResource;
    }
    public static Place getPlace(HttpServletRequest httpServletRequest, final String serviceProviderId, final String placeId)
    {
        Place aResource = null;
        
        // Start of user code getPlace
        // TODO Implement code to return a resource
        // End of user code
        return aResource;
    }
    public static Waypoint getWaypoint(HttpServletRequest httpServletRequest, final String serviceProviderId, final String waypointId)
    {
        Waypoint aResource = null;
        
        // Start of user code getWaypoint
        // TODO Implement code to return a resource
        // End of user code
        return aResource;
    }
    public static WhObject getWhObject(HttpServletRequest httpServletRequest, final String serviceProviderId, final String whObjectId)
    {
        WhObject aResource = null;
        
        // Start of user code getWhObject
        // TODO Implement code to return a resource
        // End of user code
        return aResource;
    }




    public static String getETagFromPlace(final Place aResource)
    {
        String eTag = null;
        // Start of user code getETagFromPlace
        // TODO Implement code to return an ETag for a particular resource
        // End of user code
        return eTag;
    }
    public static String getETagFromWaypoint(final Waypoint aResource)
    {
        String eTag = null;
        // Start of user code getETagFromWaypoint
        // TODO Implement code to return an ETag for a particular resource
        // End of user code
        return eTag;
    }
    public static String getETagFromWhObject(final WhObject aResource)
    {
        String eTag = null;
        // Start of user code getETagFromWhObject
        // TODO Implement code to return an ETag for a particular resource
        // End of user code
        return eTag;
    }
    public static String getETagFromMission(final Mission aResource)
    {
        String eTag = null;
        // Start of user code getETagFromMission
        // TODO Implement code to return an ETag for a particular resource
        // End of user code
        return eTag;
    }

}
