<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<%--Start of user code "Copyright"
--%>
<%--
 Copyright (c) 2011, 2012 IBM Corporation and others.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.

 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.

 Contributors:

  Andrii Berezovskyi - initial implementation of a sample delegated UI client

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>
<%--End of user code--%>

<%--Start of user code "body"
--%>
<%--TODO: Replace/adjust this default content as necessary.
All manual changes in this "protected" user code area will NOT be overwritten upon subsequent code generations.
To revert to the default generated content, delete all content in this file, and then re-generate.
--%>

<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider" %>
<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>
<%
  String creationDialogUri = request.getParameter("creationUri");
  creationDialogUri += "#oslc-core-postMessage-1.0";
%>
<html>
<head>
  <title>Creation Dialog client</title>

  <link href="<c:url value="/static/css/bootstrap-4.0.0-beta.min.css"/>" rel="stylesheet">
  <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">

  <script src="<c:url value="/static/js/jquery-3.2.1.min.js"/>"></script>
  <script src="<c:url value="/static/js/popper-1.11.0.min.js"/>"></script>
  <script src="<c:url value="/static/js/bootstrap-4.0.0-beta.min.js"/>"></script>
</head>
<body>

<nav class="navbar sticky-top navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="<c:url value="/services/catalog/singleton"/>">LocationService</a>
  </div>
</nav>

<div class="container">

  <div class="page-header">
    <h1>Creation Dialog client</h1>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-primary">
        <div class="panel-heading">Creation Dialog frame</div>
        <div class="panel-body">
          <iframe src="<%= creationDialogUri %>" id="delegatedUI"></iframe>
        </div>
        <div class="panel-footer">
          <p>URI: <em style="word-wrap:break-word;"><%= creationDialogUri %></em></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-success">
        <div class="panel-heading">Creation Dialog results</div>
        <div class="panel-body" id="results">
            <ul></ul>
        </div>
      </div>
    </div>
  </div>

</div>

<footer class="footer">
  <div class="container">
    <p class="text-muted">
      OSLC Adaptor was generated using <a href="http://eclipse.org/lyo">Eclipse Lyo</a>.
    </p>
  </div>
</footer>

<script type="text/javascript">
  $(function () {
    function handleMessage(message) {
      var results = JSON.parse(message);
      var firstResult = {
        label: results["oslc:results"][0]["oslc:label"],
        uri: results["oslc:results"][0]["rdf:resource"]
      };
      handleOslcSelection(firstResult);
    }

    function handleOslcSelection(resource) {
      $("#results ul").append('<li><a href="' + resource.uri + '"><span>' + resource.label + '</span></a></li>');
    }

    window.addEventListener('message', function (e) {
      var HEADER = "oslc-response:";
      if (e.source == document.getElementById("delegatedUI").contentWindow
          && e.data.indexOf(HEADER) == 0) {
        handleMessage(e.data.slice(HEADER.length));
      }
    }, false);
  });
</script>

</body>
</html>
<%--End of user code--%>
